### ISSUE TITLE
produce 2 same cards when set  "Delete original cards": true,

### ISSUE THREAD

**Issue by hipanda888** [Arthur-Milchior/anki-merge-notes#2]
Hi Expert,

It's a useful add-on, thank you. but still exist a bug, could you fix it.

In order to merge original 1 and 2 into 1 card and delete original cards, I set parameter "Delete original cards": true.   After I run command "Merge Notes" , ANKI produce 2 same cards (Note ID is same, Card ID is different) 

Please refer to attachement.

Regards.
Hipanda.

[Test.zip](https://github.com/Arthur-Milchior/anki-merge-notes/files/4396825/Test.zip)

**Comment by Arthur-Milchior** [comment]
The package you sent me contained a single note. So I can't reproduce the bug. Please send me the two notes you want to merge

**Comment by Arthur-Milchior** [comment]
"original 1 and 2" I 've no idea what you mean. What is "original 1 and 2" ?

**Comment by Arthur-Milchior** [comment]
You don't merge into 1 card but into 1 note. The add-on is "merge-note", I can't even imagining what "merging card" would mean in Anki

**Comment by Arthur-Milchior** [comment]
Please update and try again, I think it's corrected

**Comment by hipanda888** [comment]
Hi，I have repackaged the deck which contain 2 unmerged card .   You can execute merge operation.  if merge successfully , system will only generate 1 combined card.  but in my case , system will generate 2 same card.   My ANKI verson is Version 2.1.22 (0ecc189a)

Thanks a lot 

[Test2.zip](https://github.com/Arthur-Milchior/anki-merge-notes/files/4397005/Test2.zip)
![before](https://user-images.githubusercontent.com/62789168/77821932-0df55080-7129-11ea-9cc4-816593877337.jpg)
![after](https://user-images.githubusercontent.com/62789168/77821936-1483c800-7129-11ea-9513-ac536dc12fb6.jpg)

**Comment by hipanda888** [comment]
[Picture.zip](https://github.com/Arthur-Milchior/anki-merge-notes/files/4397011/Picture.zip)
Please refer to my picture

**Comment by hipanda888** [comment]
wonderful！ Thanks a lot!
